### PR TITLE
Fixed calculation in SQL query if there are no refunds

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fixed calculation in SQL query if there are no refunds
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Relative to #22 (Detected by @florine2623)
| How to test?  | Please indicate how to best verify that this PR is correct.

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Progi1984 ,

I'm having an issue in the total Sales in Sales and Orders stats page. 
In this example I should have €42.60 instead of €39.80
Screenshot 2021-11-29 at 13 40 19
Screenshot 2021-11-29 at 13 40 50

Could you check please ?
Thanks!

**Comment by Progi1984** [comment]
I check it in the next week ;)

**Comment by Progi1984** [comment]
@florine2623 It's logical as the calculation is based on total paid real (so that counts on payments)

**Comment by florine2623** [comment]
Hello @Progi1984 ,

I'm not sure I understand your answer.

There's always a 2.80€ difference between the displayed total Sales and the amount in the table : NOK
Here are a few examples :
Screenshot 2022-01-03 at 16 16 17
Screenshot 2022-01-03 at 16 29 18

Also, there is a lot a number after the comma, the amount is not completely visible.

**Review by matthieu-rolland — COMMENTED** [review]
Rebase needed 👍

**Comment by matks** [comment]
@Progi1984 Sorry. I don't understand how this PR went off the radar for so long.

**Review by PierreRambaud — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Thanks for the PR, it is looking good !
I tested with multiple orders, validated orders, validated then canceled orders, orders with multiple products or just one, checked CSV exports, checked distribution of order statuses, checked graphs.

It is QA ✅

**Comment by kpodemski** [comment]
Thanks @Progi1984 @florine2623

**Pull request merged**
