### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 2.1.0
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A
| Possible impacts? | N/A

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by Progi1984** [comment]
@Robin-Fischer-PS PR #24

**Comment by Progi1984** [comment]
@Robin-Fischer-PS Fixed in #24 and checked by @florine2623

**Review by jolelievre — DISMISSED** [review]
Thanks @Progi1984

**Comment by florine2623** [comment]
Hello @Progi1984 ,

I have found an issue, maybe related to https://github.com/PrestaShop/statssales/pull/17.
I should have the tax excluded total instead of €0,00 :
Screenshot 2021-11-23 at 12 09 53
Screenshot 2021-11-23 at 12 10 17

Could you take a look ?
Thanks!

**Comment by Progi1984** [comment]
@florine2623 The bugfix should be #25.

**Comment by PierreRambaud** [comment]
Waiting for #25 to be merge first

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
LGTM (not aproving before #25 is merged)

**Comment by Progi1984** [comment]
#25 is merged :tada:

**Review by PierreRambaud — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Progi1984 ,

Tested :
https://github.com/PrestaShop/statssales/pull/16
https://github.com/PrestaShop/statssales/pull/17
https://github.com/PrestaShop/statssales/pull/19
https://github.com/PrestaShop/statssales/pull/24
https://github.com/PrestaShop/statssales/pull/25
https://github.com/PrestaShop/statssales/pull/26
All these are QA ✅ 

But I'm encountering a problem while testing this one : https://github.com/PrestaShop/statssales/pull/18
The amount after a Partial Refund is OK in `Stats > Sales & Orders`, but NOK in `Dashboard`
Screenshot 2022-04-06 at 11 38 16
Screenshot 2022-04-06 at 11 37 50

Can you check please ? 
Thanks!

**Comment by Progi1984** [comment]
@florine2623 For this last bug, you should create a new issue because it's relative to the module `dashtrends`.

**Review by florine2623 — APPROVED** [review]
@Progi1984 ,

Thanks, the issue is created here : https://github.com/PrestaShop/PrestaShop/issues/28186

I haven't found any other bug nor regression on this release.
It is QA ✅

**Comment by Progi1984** [comment]
Thanks @florine2623 for this wonderful QA (and a lot of :exploding_head:).

**Comment by Robin-Fischer-PS** [comment]
Thanks @Progi1984 @florine2623 ! :tada:

**Pull request merged**
